// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniStoreManager.Data;

#nullable disable

namespace MiniStoreManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MiniStoreManager.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nước suối, trà, cà phê và nước giải khát",
                            Name = "Đồ uống"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Các mặt hàng ăn nhanh và thực phẩm khô",
                            Name = "Thực phẩm"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vật dụng thiết yếu cho cửa hàng mini",
                            Name = "Gia dụng"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sản phẩm vệ sinh và chăm sóc hằng ngày",
                            Name = "Chăm sóc cá nhân"
                        });
                });

            modelBuilder.Entity("MiniStoreManager.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "Nguyễn Minh An",
                            CustomerPhone = "0901234567",
                            OrderDate = new DateTime(2026, 6, 1, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 42000m
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "Trần Hoài Nam",
                            CustomerPhone = "0912345678",
                            OrderDate = new DateTime(2026, 6, 2, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 50000m
                        });
                });

            modelBuilder.Entity("MiniStoreManager.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            SubTotal = 12000m,
                            UnitPrice = 6000m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 2,
                            SubTotal = 30000m,
                            UnitPrice = 15000m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 2,
                            SubTotal = 24000m,
                            UnitPrice = 12000m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 1,
                            SubTotal = 22000m,
                            UnitPrice = 22000m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 2,
                            ProductId = 1,
                            Quantity = 1,
                            SubTotal = 6000m,
                            UnitPrice = 6000m
                        });
                });

            modelBuilder.Entity("MiniStoreManager.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Nước suối đóng chai tiện lợi cho khách mua lẻ.",
                            ImageUrl = "/images/water.svg",
                            Name = "Nước suối 500ml",
                            Price = 6000m,
                            Quantity = 120
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Cà phê lon dùng lạnh, bán chạy vào buổi sáng.",
                            ImageUrl = "/images/coffee.svg",
                            Name = "Cà phê lon",
                            Price = 15000m,
                            Quantity = 45
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Mì ly ăn nhanh, phù hợp khu văn phòng và ký túc xá.",
                            ImageUrl = "/images/noodle.svg",
                            Name = "Mì ly hải sản",
                            Price = 12000m,
                            Quantity = 32
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Bánh quy hộp nhỏ, dễ trưng bày tại quầy.",
                            ImageUrl = "/images/cookie.svg",
                            Name = "Bánh quy bơ",
                            Price = 28000m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Khăn giấy mềm dùng cho gia đình và văn phòng.",
                            ImageUrl = "/images/tissue.svg",
                            Name = "Khăn giấy hộp",
                            Price = 22000m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Sữa tắm dung tích nhỏ, tiện mang đi du lịch.",
                            ImageUrl = "/images/bodywash.svg",
                            Name = "Sữa tắm mini",
                            Price = 35000m,
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("MiniStoreManager.Models.OrderDetail", b =>
                {
                    b.HasOne("MiniStoreManager.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniStoreManager.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniStoreManager.Models.Product", b =>
                {
                    b.HasOne("MiniStoreManager.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniStoreManager.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniStoreManager.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MiniStoreManager.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
